
development:
  adapter: mysql
  database: gold_development
  username: root
  password: 
  host: localhost
  encoding: utf8
  
test:
  adapter: mysql
  database: gold_test
  username: root
  password: 
  host: localhost
  encoding: utf8
